#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <pthread.h>
#include <time.h>
#include <setjmp.h>
#include <linux/input.h>
/*The file descriptor for mouse events*/
#define MOUSE_EVENT_FILE   "/dev/input/event4"
/*The maximum delay that can be between 2 clicks to detect
a double click*/
#define MOUSE_CLICK_DELAY 500

/*Buffer to store the context,where the jump has to
be made*/
jmp_buf context;


/*A thread that sends a signal,when a double click is detected*/

void* mouse_thread(void* dummy)
{
	int mouse_file_desc;
	/*Input evvent parameters to store*/
	struct input_event mouse_event;
	struct timeval single_click_time,double_click_time;
	
	unsigned char click_detect = 0;
	long seconds,useconds,doubleclick_time;
	if((mouse_file_desc = open(MOUSE_EVENT_FILE, O_RDONLY)) < 0)
	{
		perror("Error opening device");
		return NULL;
	}
	/*Keep reading for any event generated by mouse*/
	while(read(mouse_file_desc, &mouse_event, sizeof(struct input_event)))
	{
		/*condition to check if it was a right click*/
		if((mouse_event.type == 1) && (mouse_event.value == 1) && (mouse_event.code == 273))
		{
			if (click_detect==0)
			{
				/*get the time for first click*/
				gettimeofday(&single_click_time,NULL);
				click_detect = 1;
				printf("\n First Right click detected\n");
			}
			else
			{
				/*Note down the time for the next click*/
				gettimeofday(&double_click_time,NULL);
				seconds  = double_click_time.tv_sec  - single_click_time.tv_sec;
				useconds = double_click_time.tv_usec - single_click_time.tv_usec;
			    doubleclick_time = ((seconds)*1000 + useconds/1000.0)+0.5;
			    /*chceck if time differnece between two clicks are less than 
			    500 milliseconds*/
			    if (doubleclick_time < MOUSE_CLICK_DELAY)
			    {
					
					printf("\n Right double click detected \n");
					/*Send the signal as soon as right click is detected*/
					kill(0,SIGUSR1);
				}
				else
				{
					/*if time difference is more than 500 ms,then use the recent
					time stamp as previous timestamp as the reference for next cycle*/
					single_click_time = double_click_time;
					
				}
			}
		}
	}
	printf("\n out of the mouse_thread");
	pthread_exit(0);
}

/*A signal handler that switches to the context stored in 
the buffer by a previous call to setjmp*/
void sig_handler(int sig_num)
{
	longjmp(context,-1);
	return;
}
int main()
{
	/*Structure to configure the signal handler*/
	struct sigaction config_sig;
	/*Structure to block a set of signals*/
	sigset_t sig_mask;
	/*Thread id for carrying out click detection*/
	pthread_t mouse_thread_id;
	int sig_result = 0;
	
	/*Create the thread for click event detection*/
	pthread_create(&mouse_thread_id,NULL,&mouse_thread,NULL);
	
   
	memset(&config_sig, 0, sizeof(config_sig));
	sigfillset(&sig_mask);
	config_sig.sa_mask = sig_mask;
	/*Assign the signal handler for signal "SIGUSR1"*/
	config_sig.sa_handler = &sig_handler;
	sigaction(SIGUSR1, &config_sig, NULL);
    printf("\n\n Right double click to stop computation ");
    /*setjmp saves the present context,when longjmp is called
    it returns -1 and breaks out of the loop of computation*/
	if (setjmp(context) == 0)
	{
		while(1)
		{
			/*keep on increasing until a signal is called, which calls longjmp
			consequently terminating the loop*/
			sig_result = sig_result + 1;
			sleep(1);
		}
	}
	else
	{
		printf("result of computation %d \n",sig_result);
	}
	return 0;
}